#!/usr/bin/env bash

if (( $# == 0 )) || [[ -z $(command -v node | grep setup/.nvm) ]] ; then
  export SETUP_RC=$HOME/.setuprc
  ( echo "export SETUP_RC=$SETUP_RC" ) > $SETUP_RC

  export HOME_PROFILE=$HOME/.profile
  SOURCE_HOME_SETUP_RC='  . "$HOME/.setuprc"'
  SOURCE_HOME_SETUP_RC_REGEX="/  \. \"\$HOME\/\.setuprc\"/p"
  if [[ $(sed -n "$SOURCE_HOME_SETUP_RC_REGEX" "$HOME_PROFILE") != $SOURCE_HOME_SETUP_RC ]] ; then
    echo 'loads setup'
    echo '# include .setuprc if it exists' >> $HOME_PROFILE
    echo 'if [ -f "$HOME/.setuprc" ] ; then' >> $HOME_PROFILE
    echo "$SOURCE_HOME_SETUP_RC" >> $HOME_PROFILE
    echo 'fi' >> $HOME_PROFILE
  fi;

  export SETUP_HOME=`dirname $(readlink -f $0)`
  ( echo "export SETUP_HOME=$SETUP_HOME" ) >> $SETUP_RC

  export NVM_DIR="$SETUP_HOME/.nvm"
  ( echo "export NVM_DIR=$NVM_DIR" ) >> $SETUP_RC
  if [[ -d $NVM_DIR ]] ; then
    echo "To update nvm"
    cd "$NVM_DIR"
    git fetch --tags origin
  else
    echo "To install nvm"
    git clone https://github.com/nvm-sh/nvm.git "$NVM_DIR"
    cd "$NVM_DIR"
  fi;
  git checkout `git describe --abbrev=0 --tags --match "v[0-9]*" $(git rev-list --tags --max-count=1)`
  cd - > /dev/null

  export NVM_SH="$NVM_DIR/nvm.sh"
  ( echo ' export NVM_SH="$NVM_DIR/nvm.sh" ' ) >> $SETUP_RC
  ( echo ' [ -s "$NVM_SH" ] && \. "$NVM_SH" # This loads nvm ' ) >> $SETUP_RC
  export NVM_BASH_COMPLETION="$NVM_DIR/bash_completion"
  ( echo ' export NVM_BASH_COMPLETION="$NVM_DIR/bash_completion" ' ) >> $SETUP_RC
  ( echo ' [ -s "$NVM_BASH_COMPLETION" ] && \. "$NVM_BASH_COMPLETION" # This loads nvm bash_completion ' ) >> $SETUP_RC

  source $SETUP_RC
  export NVM_NODEJS_ORG_MIRROR=https://nodejs.org/dist
  nvm install node
  nvm alias default node

  SETUP_NPM_BIN=`npm bin --global`
  ln -snf $SETUP_HOME/setup $SETUP_NPM_BIN/setup
fi;
echo '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'
echo 'To activate the new version of .setuprc in any new shell just run it: '
echo ' $ source $HOME/.setuprc'
echo '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'

SETUP_HOME_MAIN=$SETUP_HOME/main.js
node  --trace-warnings --experimental-wasm-modules --experimental-json-modules $SETUP_HOME_MAIN $*
